### ISSUE TITLE
Rust version of core-sys-types

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/sgx#65]
- [x] #78
- [x] Add `Report` and contained types (copy-pasta)
- [x] Add `KeyRequest`
- [x] Add `Key128Bit`
- [x] #81 
- [x] Add Fixed-size quote-related types:
    - [x] Add `QuoteNonce` (copy-pasta)
    - [x] Add `QuoteSignType` (copy-pasta)
    - [x] Add `PlatformInfoBlob` (copy-pasta)
    - [x] Add `UpdateInfo` (copy-pasta)
    - [x] Add `QlAttKeyId` and `AttKeyIdExt` (w/ readable name)
- [x] Add `EpidGroupId` (copy-pasta)

**Comment by nick-mobilecoin** [comment]
Done via, #86, #92, #103, #110, #111, #112, #113, #117, #118
