### ISSUE TITLE
Create a `mc-sgx-dcap-quoteverify` crate

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/sgx#76]
We should have idiomatic Rust APIs to wrap the DCAP quoteverify library.

**Comment by nick-mobilecoin** [comment]
blocked by #74

**Comment by nick-mobilecoin** [comment]
unblocked now that #128 is in

**Comment by nick-mobilecoin** [comment]
Done via #137, #138, and #139

`sgx_qv_free_qve_identity`, `sgx_qv_get_qve_identity`, `sgx_qv_verify_quote` are being omitted at this time.
The desire is to utilize common verify functionality that can be used consistently inside and outside of the enclave. This means that the logic will not directly rely on SGX
